#!/bin/sh

TO DO - for version 5.X
------------------------

* Fix DTMF issue in mobile call networks e.g. MTN Uganda

* Accept mDNS (224.0.0.251) packets in coova-chilli

* External players in kodi

* Home-Assistant (HASS) setups

* Userguide and Reference Manual
