#!/bin/sh

TO DO - for version 3.X
------------------------

* CRASHLOG_DIR in display.service.  kodi_crash files

* Instant recording - TVHEADEND - remote

* Picture-in-Picture (PIP)

* FM Radio

NOTE: Add above to Official FEATURES list

