#!/bin/sh

TO DO - for version 4.X
------------------------
* EPG Data for IPTV channels using XMLTV

* Accept mDNS (224.0.0.251) packets in coova-chilli

* Muted audio issue persists at JambulaTV restarts

* External players in kodi

* Speech Recognition: e.g. Say time

* FM Radio

* Userguide and Reference Manual
