#!/bin/sh
# This plugin will monitor ethernet port to see if network cable is plugged in or not
# 
# NOTE: You need to have your icinga environment properly setup
#
# Copyright (C) 2018-2018 Joseph Zikusooka.
#
# Contact me at: joseph AT zikusooka.com

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Get ethernet device
NETWORK_ETHERNET_DEVICE=$(ip link | grep '2: ' | cut -d : -f2 | head -1 | sed -e 's/ //g')
# Get ethernet IP Address
NETWORK_IP_ADDRESS=$(ip -4 addr show dev $NETWORK_ETHERNET_DEVICE | grep brd | awk {'print $2'} | cut -d / -f1)
# Get ethernet status
NETWORK_ETHERNET_STATE=$(cat /sys/class/net/$NETWORK_ETHERNET_DEVICE/carrier)



# CRITICAL - Up but no IP address assigned
if [[ "$NETWORK_ETHERNET_STATE" = "1" && "x$NETWORK_IP_ADDRESS" = "x" ]]
then
echo "CRITICAL: Ethernet Link [$NETWORK_ETHERNET_DEVICE] is DOWN"
exit 2

# OK - Up with IP address assigned
elif [[ "$NETWORK_ETHERNET_STATE" = "1" && "x$NETWORK_IP_ADDRESS" != "x" ]]
then
echo "OK: Ethernet Link [$NETWORK_ETHERNET_DEVICE] is UP"
exit 0

# OK - Down
elif [[ "$NETWORK_ETHERNET_STATE" = "0" ]]
then
echo "WARNING: Ethernet cable for [$NETWORK_ETHERNET_DEVICE] is NOT plugged in"
exit 0

else
# UNKNOWN - Unknown status
echo "WARNING: Ethernet Link status of [$NETWORK_ETHERNET_DEVICE] is UNKNOWN"
exit 1
fi
