#!/bin/sh
# Variables
PROJECT_NAME=JambulaTV
PROJECT_SYSTEM_CONF_DIR=/etc/$PROJECT_NAME
PROJECT_FUNCTIONS_FILE=$PROJECT_SYSTEM_CONF_DIR/functions
PROJECT_DVBT_SETTINGS_FILE=$PROJECT_SYSTEM_CONF_DIR/dvbt-settings.cfg
TVHEADEND_CONFIG_DIR=/JambulaTV/.hts/tvheadend
TVHEADEND_ADAPTERS_CONFIG_DIR=$TVHEADEND_CONFIG_DIR/input/linuxdvb/adapters

# Source DVBT settings file
. $PROJECT_DVBT_SETTINGS_FILE

# DVBT Adapter node
TVHEADEND_DVBT_TUNER_NODE=/dev/dvb/adapter$DVBT_TUNER_NO
# DVBT network UUID
TVHEADEND_DVBT_NETWORK_UUID=$(curl -s http://127.0.0.1:9981/api/mpegts/network/grid?limit=100000 | jq '.entries[] | select(.networkname=="'"$DVBT_NETWORK_NAME"'") |.uuid' | sed 's:"::g')

# Check if DVB network is correctly associated with the DVB-T2 tuner adapter
if [[ "x$TVHEADEND_DVBT_NETWORK_UUID" = "x" ]];
then
DVBT_NETWORK_MATCHED_WITH_TUNER=255
else
sudo grep -rli $TVHEADEND_DVBT_NETWORK_UUID $TVHEADEND_ADAPTERS_CONFIG_DIR > /dev/null 2>&1
DVBT_NETWORK_MATCHED_WITH_TUNER=$?
fi

# Icinga2 Notices
# Notice when no DVB-T Tuner is found
ICINGA2_NOTICE_CRITICAL_NO_TUNER="CRITICAL - DVB-T2 adapter was not detected. {Error: $TVHEADEND_DVBT_TUNER_NODE - No such file or directory}"
# Notice when no DVB-T Network is found
ICINGA2_NOTICE_CRITICAL_NETWORK_MISSING="CRITICAL - DVB-T2 network was not found. {Error: The network ($DVBT_NETWORK_NAME) is missing}"
# Network not associated with tuner
ICINGA2_NOTICE_CRITICAL_NETWORK_NOT_ATTACHED="CRITICAL - DVB-T2 network not assigned to TV tuner.  {Error: The adapter ($TVHEADEND_DVBT_TUNER_NODE) is missing a network}"
# Notice when all is OK
ICINGA2_NOTICE_OK="OK - DVB-T2 network and Channels list are fine"
# TVHeadend not active
ICINGA2_NOTICE_TVH_NOT_ACTIVE="The TVHeadend server is not running"



#################
#  MAIN SCRIPT  #
#################

# Quit if TVHeadend is NOT running (Unknown state)
if [[ "$(systemctl is-active tvheadend.service)" != "active" ]];
then
echo "$ICINGA2_NOTICE_TVH_NOT_ACTIVE"
exit 3
fi

# No tuner found
if [[ ! -e "$TVHEADEND_DVBT_TUNER_NODE" ]];
then
echo "$ICINGA2_NOTICE_CRITICAL_NO_TUNER"
exit 2

# Channels wiped out
elif [[ "x$TVHEADEND_DVBT_NETWORK_UUID" = "x" ]];
then
echo "$ICINGA2_NOTICE_CRITICAL_NETWORK_MISSING"
exit 2

# Network not associated with tuner
elif [[ "$DVBT_NETWORK_MATCHED_WITH_TUNER" != "0" ]];
then
echo "$ICINGA2_NOTICE_CRITICAL_NETWORK_NOT_ATTACHED"
exit 2

else
# OK
echo "$ICINGA2_NOTICE_OK"
exit 0

fi
