#!/bin/sh
# This plugin will monitor systemd and report any failed units
# 
# NOTE: You need to have your icinga environment properly setup
#
# Copyright (C) 2016-2017 Joseph Zikusooka.
#
# Contact me at: joseph AT zikusooka.com

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.



PROJECT_SYSTEM_CONF_DIR=/etc/JambulaTV
JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE=$PROJECT_SYSTEM_CONF_DIR/updates-ftp-server-cfg
JAMBULATV_RELEASE_FILE=$PROJECT_SYSTEM_CONF_DIR/release
JAMBULATV_UPDATES_TEMP_DIR=/tmp

# Source Updates FTP server information i.e. variables
. $JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE

JAMBULATV_UPDATE_CURRENT_VERSION_FILE=$(basename $JAMBULATV_FTP_SERVER_VERSION_FILE)

WGET_CMD=wget
WGET_TIMEOUT=20
WGET_OPTIONS="-q --no-check-certificate --retr-symlinks -T $WGET_TIMEOUT --ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS"
PING_COUNT=1 #9



###############
#  FUNCTIONS  #
###############
check_ftp_server_access () {
# Check for internet connectivity and access to the ftp server
host -W 1 $JAMBULATV_FTP_SERVER 8.8.8.8 > /dev/null 2>&1
EXITVAL=$?
if [ "$EXITVAL" != "0" ];
then
# Quit script, since there's no internet
exit 1
fi
}

query_and_set_versions () {
# Download latest update version info file
$WGET_CMD $WGET_OPTIONS -O $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE.$USER ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_VERSION_FILE
#
# Exit updater if ftp login fails; and log error
if [ "$?" = "0" ];
then
# Set latest update revision
JAMBULATV_LATEST_UPDATE_VERSION=$(cat $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE.$USER)
# Lookup current version
JAMBULATV_INSTALLED_VERSION=$(grep -i Version $JAMBULATV_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
else
exit 1
fi
}



#################
#  MAIN SCRIPT  #
#################

check_ftp_server_access 

query_and_set_versions 

# Quit if JambulaTV is upto update.  
if [ $(echo "$JAMBULATV_LATEST_UPDATE_VERSION <= $JAMBULATV_INSTALLED_VERSION" | bc -l) = 1 ] || [ "x$JAMBULATV_LATEST_UPDATE_VERSION" = "x" ];
then

# No Updates Available
echo "Up to Date"
exit 0

else
echo "Update Available: $JAMBULATV_LATEST_UPDATE_VERSION"
exit 2

fi
