#!/bin/sh
MY_WIFI_DEVICES_FILE=/etc/JambulaTV/my-wifi-devices.cfg

WIFI_DEVICE_ADDRESS=$(echo $2 | sed "s/:/-/g")
WIFI_DEVICE_USER="$(cat $MY_WIFI_DEVICES_FILE | grep -Ev '(#.*$)|(^$)' | grep -i $WIFI_DEVICE_ADDRESS | cut -d '|' -f2 | sed 's:^ ::' | sed 's: *$::g')"
WIFI_MONITORED="$(cat $MY_WIFI_DEVICES_FILE | grep -Ev '(#.*$)|(^$)' | grep -i $WIFI_DEVICE_ADDRESS | cut -d '|' -f3 | sed 's:^ ::')"



###############
#  FUNCTIONS  #
###############

scan_4_wifi_device () {

# Scan for WiFi device
sudo /usr/sbin/hostapd_cli sta $(echo $WIFI_DEVICE_ADDRESS | sed "s/-/:/g") | grep -i connected_time > /dev/null 2>&1
SCAN_RESULT=$?
#
#
# Test for availabilty of monitored users
if [ "$SCAN_RESULT" -eq "0" ] && [ "$WIFI_MONITORED" = "yes" ];
then

echo "$WIFI_DEVICE_USER is Present"
exit 0

else
echo "$WIFI_DEVICE_USER is Absent"

exit 2
fi

}



#################
#  MAIN SCRIPT  #
#################

scan_4_wifi_device 
