#!/bin/sh
# Available in functions file
INTERNET_WIFI_ISP_CONFIG=/etc/JambulaTV/internet-mobile-wifi.cfg
WIFI_WPA_CONFIG_FILE=/etc/wpa_supplicant/wpa_supplicant.conf
WIFI_INTERFACES_AVAILABLE=$(sudo ip link |grep jwlan | wc -l)
# Variable specific to this script
WIFI_SSID=$(grep -i SSID $INTERNET_WIFI_ISP_CONFIG | sed '/^#/d' | cut -d = -f2 | sed 's/"//g')
# Set WiFi station Interface
WIFI_STATION_INTERFACE=MY_WIFI_STATION_INTERFACE



###############
#  FUNCTIONS  #
###############
number_of_interfaces () { 
# Quit if less than 2 WiFi devices are detected
if [ "$WIFI_INTERFACES_AVAILABLE" -lt "2" ];
then
echo "CRITICAL: Sorry, I did not find a second and/or usable WiFi interface "
exit 2
fi
}

type_of_station_interface () {
# Unsupported r8188eu devices like RTL8188ETV, RTL8188EUS (TP-Link TL-WN723/TL-WN725N)
journalctl -b -o cat --no-pager | grep $WIFI_STATION_INTERFACE | grep r8188eu > /dev/null 2>&1
UNSUPPORTED=$?
# Check to see if supported
if [ "$UNSUPPORTED" = "0" ];
then
IW_COMPATIBLE=no
else
IW_COMPATIBLE=yes
fi
}

scan_4_wifi () {
# Take station UP
sudo ip link set $WIFI_STATION_INTERFACE up
#
# Scan for AP, and get scanned SSID
if [ "$IW_COMPATIBLE" = "yes" ];
then
# Using iw command
sudo iw dev $WIFI_STATION_INTERFACE scan | grep -w "SSID: $WIFI_SSID" > /dev/null 2>&1
AP_EXISTENCE=$?
else
# Using iwlist command
sudo iwlist $WIFI_STATION_INTERFACE scan | grep -w "ESSID:\"$WIFI_SSID\"" > /dev/null 2>&1
AP_EXISTENCE=$?
fi
}



#################
#  MAIN SCRIPT  #
#################
number_of_interfaces
type_of_station_interface
scan_4_wifi

# See if there's a match for my AP
if [ "$AP_EXISTENCE" = "0" ];
then
echo "OK - Wireless Access Point ($WIFI_SSID) Available"
exit 0

else
echo "WARNING - Wireless Access Point ($WIFI_SSID) Not Available"
exit 1

fi
