#!/bin/sh
# This plugin will monitor systemd and report any failed units
# 
# NOTE: You need to have your icinga environment properly setup
#
# Jambula Labs @copyright 2019-2020 All rights reserved
#
# Source global settings
PROJECT_NAME=JambulaTV
PROJECT_SYSTEM_CONF_DIR=/etc/$PROJECT_NAME
PROJECT_GLOBAL_SETTINGS_FILE=$PROJECT_SYSTEM_CONF_DIR/global-settings.cfg
. $PROJECT_GLOBAL_SETTINGS_FILE

# Variables
JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE=$PROJECT_SYSTEM_CONF_DIR/updates-ftp-server-cfg
JAMBULATV_RELEASE_FILE=$PROJECT_SYSTEM_CONF_DIR/release
JAMBULATV_UPDATES_TEMP_DIR=/tmp

# Source Updates FTP server information i.e. variables
. $JAMBULATV_UPDATES_FTP_SERVER_INFO_FILE

JAMBULATV_UPDATE_CURRENT_VERSION_FILE=$(basename $JAMBULATV_FTP_SERVER_VERSION_FILE)

WGET_CMD=wget
WGET_TIMEOUT=20
WGET_OPTS="-q --no-check-certificate --retr-symlinks -T $WGET_TIMEOUT --ftp-user=$JAMBULATV_FTP_USER --ftp-password=$JAMBULATV_FTP_PASS"
PING_COUNT=1 #9
PING_IP_ADDRESS=$PING_IP_ADDRESS



###############
#  FUNCTIONS  #
###############
check_ftp_server_access () {
# Check for internet connectivity - IMPORTANT: Don't use DNS to ping use actual IP address
ping -c $PING_COUNT $PING_IP_ADDRESS > /dev/null 2>&1
EXITVAL=$?
if [ "$EXITVAL" != "0" ];
then
# Quit script, since there's no internet
exit 0
fi
}

query_and_set_versions () {
# Download latest update version info file
$WGET_CMD $WGET_OPTS -O $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE.$USER ftp://$JAMBULATV_FTP_SERVER/$JAMBULATV_FTP_SERVER_VERSION_FILE
#
# Exit updater if ftp login fails; and log error
if [ "$?" = "0" ];
then
# Set latest update revision
JAMBULATV_LATEST_UPDATE_VERSION=$(cat $JAMBULATV_UPDATES_TEMP_DIR/$JAMBULATV_UPDATE_CURRENT_VERSION_FILE.$USER)
# Lookup current version
JAMBULATV_INSTALLED_VERSION=$(grep -i Version $JAMBULATV_RELEASE_FILE | cut -d : -f2 | sed 's:v::g')
else
exit 0
fi
}



#################
#  MAIN SCRIPT  #
#################

check_ftp_server_access 

query_and_set_versions 

# Quit if JambulaTV is upto update.  
if [ $(echo "$JAMBULATV_LATEST_UPDATE_VERSION <= $JAMBULATV_INSTALLED_VERSION" | bc -l) = 1 ] || [ "x$JAMBULATV_LATEST_UPDATE_VERSION" = "x" ];
then

# No Updates Available
echo "Up to Date"
exit 0

else
echo "Update Available: $JAMBULATV_LATEST_UPDATE_VERSION"
exit 2

fi
