#!/bin/sh
# This script is used by icinga2 to check for availability of preferred
# wireless access point
#
# Jambula Labs @copyright 2020-2021 All rights reserved

# Available in functions file
INTERNET_WIFI_ISP_CONFIG=/etc/JambulaTV/internet-mobile-wifi.cfg
WIFI_WPA_CONFIG_FILE=/etc/wpa_supplicant/wpa_supplicant.conf
WIFI_INTERFACES_AVAILABLE=$(sudo /usr/sbin/ip link | grep jwlan | wc -l)
# Variable specific to this script
WIFI_SSID=$(grep -i SSID $INTERNET_WIFI_ISP_CONFIG | sed '/^#/d' | cut -d = -f2 | sed 's/"//g')
# Set WiFi station Interface
WIFI_STATION_INTERFACE=MY_WIFI_STATION_INTERFACE



###############
#  FUNCTIONS  #
###############
number_of_interfaces () { 
# Quit if less than 2 WiFi devices are detected
if [ "$WIFI_INTERFACES_AVAILABLE" -lt "2" ];
then
echo "CRITICAL: Sorry, I did not find a second and/or usable WiFi interface "
exit 2
fi
}

scan_4_wifi () {
# Take station UP
sudo /usr/sbin/ip link set $WIFI_STATION_INTERFACE up
# Scan for AP and pick out preferred SSID
sudo /usr/bin/iwctl station $WIFI_STATION_INTERFACE scan
DISCOVERED_WIFI_SSID=$(sudo /usr/bin/iwctl station $WIFI_STATION_INTERFACE get-networks | awk '/*/ {print $1}' | sed 's/>//g' | sed -n "/^$WIFI_SSID$/p")
}



#################
#  MAIN SCRIPT  #
#################

# Check for number of WiFi devices
number_of_interfaces

# Scan for available WiFi networks
scan_4_wifi

# See if there's a match for my AP
if [[ "x$DISCOVERED_WIFI_SSID" != "x" ]];
then
echo "OK - Wireless Access Point ($WIFI_SSID) Available"
exit 0

else
echo "WARNING - Wireless Access Point ($WIFI_SSID) Not Available"
exit 1

fi
