#!/bin/sh
# This plugin will monitor systemd and report any failed units
# 
# NOTE: You need to have your icinga environment properly setup
#
# Copyright (C) 2015-2016 Joseph Zikusooka.
#
# Contact me at: joseph AT zikusooka.com

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.



# Wait until all systemd services have run i.e. Wait until boot up is complete
systemd-analyze | grep finished > /dev/null 2>&1
STARTUP_FINISHED=$?
# Uptime in seconds
UPTIME_SECS=$(cat /proc/uptime | awk {'print $1'} | cut -d . -f1)

# Quit if system just booted.  Most times gives false positives
if [ "$STARTUP_FINISHED" != "0" ] || [ "$UPTIME_SECS" -lt "180" ];
then
echo "Dont worry, Systemd just booted up.  Will clear this warning shortly"
exit 1
fi

# Get failed units
FAILED_UNITS=$(systemctl --failed --no-legend | awk {'print $5'})

if [ "x$FAILED_UNITS" = "x" ];
then

# Normal
echo "OK: Systemd is doing well"
exit 0

else
echo "CRITICAL: Systemd has some failed units: $(echo $FAILED_UNITS)"
exit 2

fi
