#!/bin/sh


samba_configure () {

systemctl enable smb.service
systemctl enable nmb.service

Fix smb.conf
See:workspace.REMOVE/smb_conf.patch
}




Left :TO DO here:
----------------
- Accounting - Time left
- Change Graphics of Woman and Dog in HTML splash files





OPEN HOTEL:
===========
- To fix SQLSTATE error suring final profile install:
max_execution_time = 120 to /etc/php.ini

- To Fix 'MySQL has gone away error:'
max_allowed_packet = 32M to /etc/my.cnf [mysqld]


# FIXES:
# ++++++++
echo "# Clean tmp files - systemd-44-24.fc17 filling up /tmp very quickly
d /tmp 1777 root root 6h
d /var/tmp 1777 root root 1d" > /etc/tmpfiles.d/tmp.conf

# Bash copy more than 50 lines - .vimrc
set history=1000 "Command line history
set viminfo='20,\"1000 " Copy upto 1000


# Journal
/etc/systemd/journald.conf
SystemMaxUse=100M 

ForwardToSyslog=no


1. AP and Station WiFi using same interface like connectify in windows

1. RSS ticker (add twitter feeds?)

2. Radio feeds - UG

3. rtGui - rtorrents

4. Weather Feeds

6. Add Files

7. LOGOs for TV

8. IPTV feeds

* PIP

* Listen to FM Radio

* Stream FM Radio to any IP enabled device in your house.  This means you can listen to your favorite local FM stations on your phone or tablet any where in the house.

* FM Radio recording of your favorite shows while you watch TV or video

* Headlines: RSS reader to download and read the latest headlines

* Picture-in-Picture (PIP) – While watching another TV channel or while seeing a Movie

* Remind:  Do not miss any important events such as Birthdays, Anniversaries, Weddings etc

* Computer mode: Function as a normal computer

* Bluetooth Presence

* View and import images from a digital camera

* A full feldged phone communications system with Voicemail and VOIP capabilities

* On-screen Caller-ID: Display of incoming calls while watching TV or movies

* USB device support: Flash disk, Camera, iPOD, Hard Drive, 

* Auto wakeup and shutdown on idle

* Access CCTV on mobile or any device with a web browser - Montage View

* SIP WebRTC phone



FUTURE:
--------

* Games
- Play Linux games for example Torcs, vdrift, childsplay, FlightGear
- Play PlayStation one Games 

* Hookup to DSTV, GoTV, Star Times, Zuku, and other Pay TV providers

* FlexGet
- Catch up on popular TV shows like Homeland, Game of Thrones, Walking Dead.
- Your shows are automatically downloaded as soon as they become available
- Enter a movie in your queue, and it will be downloaded automatically

- Download video podcasts from RSS feed
- Download audio podcasts files from RSS feeds.


* Control home automation equipment (lights, sockets etc.)
