#!/usr/bin/env bash
template=$(cat <<TEMPLATE

$NOTIFICATIONTYPE
$HOSTALIAS
$HOSTADDRESS
$HOSTSTATE
$LONGDATETIME
$HOSTOUTPUT
$NOTIFICATIONAUTHORNAME
$NOTIFICATIONCOMMENT
$HOSTDISPLAYNAME
$USEREMAIL

TEMPLATE
)

sudo /usr/bin/jambulatv-dns-status-triggers $HOSTSTATE
