#!/usr/bin/env bash
#
# Available runtime macros - See commands.conf
# HOSTALIAS
# HOSTADDRESS
# HOSTSTATE
# HOSTSTATEID
# HOSTSTATETYPE
# HOSTOUTPUT
# HOSTDISPLAYNAME
# LASTHOSTSTATE
# LASTEHOSTSTATEID
# LASTHOSTSTATETYPE
# LASTHOSTSTATECHANGE
# LASTHOSTCHECK
# LONGDATETIME

sudo /usr/bin/jambulatv-dns-status-triggers $HOSTSTATE $LASTHOSTSTATE
