#!/usr/bin/env bash
template=$(cat <<TEMPLATE

$HOSTALIAS
$HOSTADDRESS
$HOSTSTATE
$HOSTSTATEID
$HOSTSTATETYPE
$HOSTOUTPUT
$HOSTDISPLAYNAME
$LASTHOSTSTATE
$LASTHOSTSTATETYPE
$LASTHOSTSTATECHANGE
$LASTHOSTCHECK
$LONGDATETIME

TEMPLATE
)

sudo /usr/bin/jambulatv-presence-detection $HOSTSTATE "$HOSTDISPLAYNAME"
